# ???????????? ???? "??????"

# ?????? ???????? ???? (? ???????)
# ?????? ???? = ????? ?????????? ????
grid.size=15

# ???????? ???? (???????? ????? ?????? ? ?????????????)
game.speed=100

# ???????????? ????????????????? ???? (? ????????)
game.duration=300

# ????????? ????? ??????
snake.initial.length=3

# ??????? ???? ???? (? ????????)
game.window.width=600
game.window.height=600